### ISSUE TITLE
Bug in Matrix2D class 

### ISSUE THREAD

**Issue by dimtsap** [isaar/MSolve#116]
CAUTION! For some reason when using the operator * to multiply a scalar with a matrix, the initial matrix values are scaled instead of returning a scaled copy of the matrix.

**Comment by SerafeimBakalakos** [comment]
In ISAAR.MSolve.Numerical.LinearAlgebra.Matrix2D.cs replace 

        public static Matrix2D operator *(Matrix2D A, double b)
        {
            Matrix2D AA = new Matrix2D(A.data as double[,]);
            for (int i = 0; i < A.Rows; i++)
                for (int j = 0; j < A.Columns; j++)
                    AA[i, j] = AA[i, j] * b;
            return AA;
        }

with

        public static Matrix2D operator *(Matrix2D A, double b)
        {
            var scaled = new Matrix2D(new double[A.Rows, A.Columns]);
            Array.Copy(A.data, scaled.data, A.data.Length);
            scaled.Scale(b);
            return scaled;
        }

I have already done so and it doesn't seem to break anything else. Only IGA code uses that operator as far as my repo knows, so let's hope no one else depends on that side effect. The change will also be included in my next pull request.

**Comment by SerafeimBakalakos** [comment]
This was fixed at some point. Anyway this class is no longer in use as of #126.
