### ISSUE TITLE
[Elem] Plane stress

### ISSUE THREAD

**Issue by GoatOfRafin** [isaar/MSolve#12]
Plane stress elements need to be implemented (@isaar/formulation)

**Comment by pmetsis** [comment]
George i 'll try to implement the simple QUAD 4 Element.

**Comment by SerafeimBakalakos** [comment]
As of #81, any (geometrically linear) 2D continuum element can be easily obtained by just adding a class that implements its shape functions. Plane stress/strain is handled by specifying the correct material. The basic ones (Quad4, Quad8, Quad9, Tri3, Tri6) have been implemented as of #95. #103 did the same for 3D continuum elements.
