### ISSUE TITLE
[IGA] Preprocessor extension to support Isogeometric AnaLysis

### ISSUE THREAD

**Issue by dimtsap** [isaar/MSolve#26]
## **Extension to implement:**

**Entities**
- Control Points (Parametric/Cartesian) 
- Knots 
- NURBS Elements
- Bezier Elements

**Model for IGA**
- Subdomains extended to include Patches
- Element -> Supportive -> Gauss Quadrature for more than 3 points
- Readers -> Implement Reader for IGA

**Problem**
- Isogeometric

**Comment by mtripakis** [comment]
Extension of the functionality to read various formats of standard nurbs geometry input files (IGES etc).
