### ISSUE TITLE
[Core] Addition of Outer Product method into Vector

### ISSUE THREAD

**Issue by VasilisMerevis** [isaar/MSolve#36]
Method to calculate the outer product of two vectors. Basically it represents the tensor product of two first order tensors (vectors). Also known as dyadic product.

References:
- [https://en.wikipedia.org/wiki/Outer_product](url)
- Matrix Algebra: Theory, Computations, and Applications in Statistics, James E. Gentle (page 69)
- Tensor Properties of Solids, Richard F. Tinder (page 27)

**Comment by SerafeimBakalakos** [comment]
Added in #118.
