### ISSUE TITLE
Materials should probably not be a part of FEM project

### ISSUE THREAD

**Issue by mariatav** [isaar/MSolve#60]
@GoatOfRafin @dimtsap @SerafeimBakalakos 
The materials classes should probably not be part of the FEM project, since all they should get as input/output are strains/stresses, which are independent of the finite element method. Therefore, they could be reused by all formulations solving problems pertaining to material stresses/strains (as opposed to for example thermal state), and could be used by isogeometric or meshless or xfem formulations.

**Comment by GoatOfRafin** [comment]
This is why we have the MaterialsTest library; the separation of materials from FEM was long ago decided and your support on proceeding to that is welcome (or expected I would say)

**Comment by GoatOfRafin** [comment]
@mariatav 
Materials should be renamed into constitutive laws (or similar) and be detached from FEM as you said and somehow related to the Problems project. This means that:

[] Elements of FEM, IGA or whatever other should be able to use different constitutive models depending on the problem
[] Problems should define which constitutive models should be allowed

Example: Structural problem should have material constitutive laws, Porous problem should have both material and permeability constitutive law, Heat transfer should have conductivity laws. All problems should be able to use generic elements from the spatial discretization projects

**Comment by mariatav** [comment]
Assigned to me, deadline till Thursday.

**Comment by mariatav** [comment]
Example for finite elements for heat transfer: [http://www.springer.com/cda/content/document/cda_downloaddocument/9781848829718-c1.pdf?SGWID=0-0-45-855604-p173938034](url)

**Comment by GoatOfRafin** [comment]
Useful, verifies the fact that differential operators differ according to the PDE that model the problem at hand.

**Comment by SerafeimBakalakos** [comment]
This separation was completed in #65
