### ISSUE TITLE
Move optimization benchmarks. 

### ISSUE THREAD

**Issue by mariatav** [isaar/MSolve#63]
@GoatOfRafin @SerafeimBakalakos 

The benchmarks folder in Optimization project probably needs to be incorporated into the Tests project, along with the OptimizationTests project.

**Comment by SerafeimBakalakos** [comment]
Nope, they are not tests. They are meant to assess the performance of optimization algorithms, not the correctness or performance of the code itself. They could be used as unit/integration tests under circumstances, in which case they would probably need to interface with other modules (e.g. FEM). That code does belong in the OptimizationTests project. However, the description of the benchmarks should not have such dependencies (it currently does unfortunately) and it belongs in in the Optimization project.
