### ISSUE TITLE
Analyzers - Newton Raphson benchmark examples

### ISSUE THREAD

**Issue by mariatav** [isaar/MSolve#71]
The geometrically non-linear hexa element  of @Gerasimos01 (which is used in a benchmark example for newton-raphson) needs to be added (maybe to the UnitTests project for starters).

**Comment by dimtsap** [comment]
@gsoim We should also format this non-linear Hexa Element to make it a paradigm of how we should all write new Elements from now on.

**Comment by SerafeimBakalakos** [comment]
Geometrically non linear Hexa8 element was added in #106. A nice template for writing continuum elements was provided in #81, #103. It still needs to be extended to geometrically non linear ones.
