### ISSUE TITLE
[Opti] Particle Swarm method

### ISSUE THREAD

**Issue by GoatOfRafin** [isaar/MSolve#8]
The Particle Swarm method needs to be implemented (@isaar/opti)

**Comment by vpapado** [comment]
Refer to @GoatOfRafin for instructions

**Comment by SerafeimBakalakos** [comment]
A bare-bones implementation has been added by @geoem (long ago).

**Comment by SerafeimBakalakos** [comment]
A basic implementation has been added by @geoem (long ago).
