### ISSUE TITLE
Displacement Control - problem with GlobalMatrixAssemblerSkyline

### ISSUE THREAD

**Issue by gsoim** [isaar/MSolve#80]
Stiffness Matrix K_fp pertaining to constrained degrees of freedom is non-symmetric and non-square.

**Comment by SerafeimBakalakos** [comment]
This was addressed by multiplying Kfp * du at each element and then assembling the equivalent forces vector. Also #123 added the option to create the whole stiffness matrix: K = [Kff Kfp; Kpf Kpp] (f=free dofs, p = prescribed displacement dofs).

**Comment by SerafeimBakalakos** [comment]
This was addressed by multiplying Kfp * du at each element and then assembling the equivalent forces vector. Also #123 added the option to create the whole stiffness matrix: K = [Kff Kfp; Kpf Kpp] (f=free dofs, p = prescribed displacement dofs).
