### ISSUE TITLE
[Opti] Genetic algorithm

### ISSUE THREAD

**Issue by GoatOfRafin** [isaar/MSolve#9]
The genetic algorithm needs to be implemented (@isaar/opti)

**Comment by SerafeimBakalakos** [comment]
Basic implementations of Genetic Algorithm and Real Coded Genetic Algorithm have been added (long ago)

**Comment by SerafeimBakalakos** [comment]
Basic implementations of Binary and Real Coded Genetic Algorithms have been added long ago.
